version: "3"

services:
  frontend:
    image: reacttyping/front
    build:
      context: .
      dockerfile: Dockerfile.front
    command: "yarn start"
    ports:
      - "3000:3000"
    volumes:
      - ./front:/usr/src/app
    tty: true

  # api:
  #   image: soreiyu/api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.api
  #   command: "yarn start"
  #   ports:
  #     - "9999:9999"
  #   volumes:
  #     - ./api:/usr/src/app